### ISSUE TITLE
corrupted NEXRAD file triggers R session abort

### ISSUE THREAD

**Issue by iskandari** [adokter/vol2birdR#61] opened 2024-03-05 17:33 UTC
Reproducible with attached pvol:
[KLCH20010308_191855.gz](https://github.com/adokter/vol2birdR/files/14499151/KLCH20010308_191855.gz)

```r
vol2birdR::vol2bird('KLCH20010308_191855.gz')
```

- Check for pvol integrity before running `vol2bird()`

**Comment by adokter** [comment] 2024-03-06 02:13
Reported by Kyle Horton: _I see a number of files, usually older, that make R abort when running calculate_vp. I think the issue is because the file has too many azimuths (364, 366, etc.). It looks like bioRad starts to resample, but then the R Session aborts. I was wondering if you've encountered this and whether you have a way of checking if the file is corrupt before trying to do any processing? Maria tried reading in some of the bad files in Python and it throws an error, stating that the file is bad, rather than crashing. Any thoughts? I attached one of the files that is causing this issue._

**Comment by adokter** [comment] 2024-03-06 02:16
The issue is caused by a segfault:

```
vol2bird.sh KLCH20010308_191855.gz 
Loaded user configuration file 'options.conf' ...
Filename = KLCH20010308_191855.gz, callid = KLCH
Reading RSL polar volume with nominal time 20010308-191856, source: RAD:KLCH,PLC:LAKE_CHARLES,state:LA,radar_name:KLCH
Warning: resampling DBZH sweep at elevation 0.490822 (367 rays into 360 azimuth-bins) ...
Warning: RSL sweep of volume 1 not found by PolarScanParam_RSL2Rave...
PolarScanParam_RSL2Rave returned empty object for parameter 1
Warning: resampling DBZH sweep at elevation 1.511024 (367 rays into 360 azimuth-bins) ...
Warning: resampling VRADH sweep at elevation 1.511024 (367 rays into 360 azimuth-bins) ...
 2024/03/06 02:15:03 :     WARNING : Different number of rays/bins for various parameters are not allowed (polarscan.c:778)
Warning: dimensions of scan parameter 1 at elev 1.511024 do not match scan dimensions, resampling ...
Warning: resampling WRADH sweep at elevation 1.511024 (367 rays into 360 azimuth-bins) ...
 2024/03/06 02:15:03 :     WARNING : Different number of rays/bins for various parameters are not allowed (polarscan.c:778)
Warning: dimensions of scan parameter 2 at elev 1.511024 do not match scan dimensions, resampling ...
Warning: resampling DBZH sweep at elevation 2.436713 (361 rays into 360 azimuth-bins) ...
Warning: resampling VRADH sweep at elevation 2.436713 (361 rays into 360 azimuth-bins) ...
 2024/03/06 02:15:03 :     WARNING : Different number of rays/bins for various parameters are not allowed (polarscan.c:778)
Warning: dimensions of scan parameter 1 at elev 2.436713 do not match scan dimensions, resampling ...
Warning: resampling WRADH sweep at elevation 2.436713 (361 rays into 360 azimuth-bins) ...
 2024/03/06 02:15:03 :     WARNING : Different number of rays/bins for various parameters are not allowed (polarscan.c:778)
Warning: dimensions of scan parameter 2 at elev 2.436713 do not match scan dimensions, resampling ...
Warning: resampling DBZH sweep at elevation 3.405223 (367 rays into 360 azimuth-bins) ...
Warning: resampling VRADH sweep at elevation 3.405223 (367 rays into 360 azimuth-bins) ...
 2024/03/06 02:15:03 :     WARNING : Different number of rays/bins for various parameters are not allowed (polarscan.c:778)
Warning: dimensions of scan parameter 1 at elev 3.405223 do not match scan dimensions, resampling ...
Warning: resampling WRADH sweep at elevation 3.405223 (367 rays into 360 azimuth-bins) ...
 2024/03/06 02:15:03 :     WARNING : Different number of rays/bins for various parameters are not allowed (polarscan.c:778)
Warning: dimensions of scan parameter 2 at elev 3.405223 do not match scan dimensions, resampling ...
Warning: resampling DBZH sweep at elevation 4.327955 (367 rays into 360 azimuth-bins) ...
Warning: resampling VRADH sweep at elevation 4.327955 (367 rays into 360 azimuth-bins) ...
 2024/03/06 02:15:03 :     WARNING : Different number of rays/bins for various parameters are not allowed (polarscan.c:778)
Warning: dimensions of scan parameter 1 at elev 4.327955 do not match scan dimensions, resampling ...
Warning: resampling WRADH sweep at elevation 4.327955 (367 rays into 360 azimuth-bins) ...
 2024/03/06 02:15:03 :     WARNING : Different number of rays/bins for various parameters are not allowed (polarscan.c:778)
Warning: dimensions of scan parameter 2 at elev 4.327955 do not match scan dimensions, resampling ...
Warning: resampling DBZH sweep at elevation 6.040573 (357 rays into 360 azimuth-bins) ...
Warning: resampling VRADH sweep at elevation 6.040573 (357 rays into 360 azimuth-bins) ...
 2024/03/06 02:15:03 :     WARNING : Different number of rays/bins for various parameters are not allowed (polarscan.c:778)
Warning: dimensions of scan parameter 1 at elev 6.040573 do not match scan dimensions, resampling ...
Warning: resampling WRADH sweep at elevation 6.040573 (357 rays into 360 azimuth-bins) ...
 2024/03/06 02:15:03 :     WARNING : Different number of rays/bins for various parameters are not allowed (polarscan.c:778)
Warning: dimensions of scan parameter 2 at elev 6.040573 do not match scan dimensions, resampling ...
Warning: resampling DBZH sweep at elevation 9.913390 (366 rays into 360 azimuth-bins) ...
Warning: resampling VRADH sweep at elevation 9.913390 (366 rays into 360 azimuth-bins) ...
 2024/03/06 02:15:03 :     WARNING : Different number of rays/bins for various parameters are not allowed (polarscan.c:778)
Warning: dimensions of scan parameter 1 at elev 9.913390 do not match scan dimensions, resampling ...
Warning: resampling WRADH sweep at elevation 9.913390 (366 rays into 360 azimuth-bins) ...
 2024/03/06 02:15:03 :     WARNING : Different number of rays/bins for various parameters are not allowed (polarscan.c:778)
Warning: dimensions of scan parameter 2 at elev 9.913390 do not match scan dimensions, resampling ...
Warning: resampling DBZH sweep at elevation 14.620268 (364 rays into 360 azimuth-bins) ...
Warning: resampling VRADH sweep at elevation 14.620268 (364 rays into 360 azimuth-bins) ...
 2024/03/06 02:15:03 :     WARNING : Different number of rays/bins for various parameters are not allowed (polarscan.c:778)
Warning: dimensions of scan parameter 1 at elev 14.620268 do not match scan dimensions, resampling ...
Warning: resampling WRADH sweep at elevation 14.620268 (364 rays into 360 azimuth-bins) ...
 2024/03/06 02:15:03 :     WARNING : Different number of rays/bins for various parameters are not allowed (polarscan.c:778)
Warning: dimensions of scan parameter 2 at elev 14.620268 do not match scan dimensions, resampling ...
/opt/vol2bird/vol2bird/bin/vol2bird.sh: line 4: 24687 Segmentation fault: 11  /opt/vol2bird/vol2bird/bin/vol2bird "$@"
```

**Comment by adokter** [comment] 2024-03-07 01:24
Valgrind indicates the segfault occurs at this line:
https://github.com/adokter/vol2birdR/blob/069b735ff778f223e3547dfcba3d7b257ecbecbc/src/libvol2bird/librsl.c#L290

```
==225476== Invalid read of size 4
==225476==    at 0x4871B78: PolarScan_RSL2Rave (librsl.c:290)
==225476==    by 0x4871B78: PolarScan_RSL2Rave (librsl.c:244)
==225476==    by 0x4872348: PolarVolume_RSL2Rave (librsl.c:456)
==225476==    by 0x4872348: PolarVolume_RSL2Rave (librsl.c:356)
==225476==    by 0x4872645: vol2birdGetRSLVolume (librsl.c:528)
==225476==    by 0x10A908: main (vol2bird.c:310)
==225476==  Address 0x94 is not stack'd, malloc'd or (recently) free'd
```

**Comment by adokter** [comment] 2024-03-07 01:43
fixed by https://github.com/adokter/vol2birdR/commit/df7b22e8ee44cae1e62c59921bac685a220f2238

**Closed by adokter** 2024-03-07 01:43 UTC
